apiVersion: v1
kind: Service
metadata:
  name: godjira-web-service
  namespace: godjira
  labels:
    app: godjira-web
    component: frontend
    tier: presentation
spec:
  type: ClusterIP
  selector:
    app: godjira-web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: None
